version: '3.9'

services:

  postgres-room:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres-single
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=room_service_db
    volumes:
      - ./data/room:/var/lib/postgresql/data/
      - ./init/room/init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-single
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password

