version: '3.9'

services:

  mongodb-booking:
    image: mongo:latest # put the version which you want to use
    container_name: mongodb-booking
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init/booking/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./data/booking:/data/db
    command: mongod --auth


  mongo-express-booking:
    image: mongo-express
    ports:
      - "8086:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-booking
    depends_on:
      - mongodb-booking
    container_name: mongo-express-booking
