version: '3.9'

services:

  mongodb-approval:
    image: mongo:latest # put the version which you want to use
    container_name: mongodb-approval
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init/approval/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./data/approval:/data/db
    command: mongod --auth


  mongo-express-approval:
    image: mongo-express
    ports:
      - "8088:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-approval
    depends_on:
      - mongodb-approval
    container_name: mongo-express-approval
