version: '3.9'

services:

  mongodb-event:
    image: mongo:latest # put the version which you want to use
    container_name: mongodb-event
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./init/event/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./data/event:/data/db
    command: mongod --auth


  mongo-express-event:
    image: mongo-express
    ports:
      - "8087:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb-event
    depends_on:
      - mongodb-event
    container_name: mongo-express-event
